//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace library.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int ID_j { get; set; }
        public Nullable<int> ID_bk { get; set; }
        public Nullable<int> ID_us { get; set; }
        public Nullable<System.DateTime> date_of_issue { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual books books { get; set; }
        public virtual user user { get; set; }
    }
}
