//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace library.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class publishing
    {
        public int ID_pg { get; set; }
        public string name { get; set; }
    }
}
