//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace library.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.user = new HashSet<user>();
        }
    
        public int ID_r { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<user> user { get; set; }
    }
}
